sudo: required
services:
  - docker

before_install:
  - docker build -t rperezvicente/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rperezvicente/react-test npm test -- --coverage

after_success:
  - docker build -t rperezvicente/multi-client ./client
  - docker build -t rperezvicente/multi-nginx ./nginx
  - docker build -t rperezvicente/multi-server ./server
  - docker build -t rperezvicente/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push rperezvicente/multi-client
  - docker push rperezvicente/multi-nginx
  - docker push rperezvicente/multi-server
  - docker push rperezvicente/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-097101388059"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
